name: Release Terraform

on:
  push:
    branches: [main]

jobs:
  semantic-release:
    name: Run semantic-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para que semantic-release vea todos los tags

      - name: Setup Node.js
        uses: actions/setup-node@v4.0
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
